wx-Page({

    /**
     * 页面的初始数据
     */
    data: {
      
    },
    check_detail1:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=0'
      })
    },
    check_detail2:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=1'
      })
    },
    check_detail3:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=2'
      })
    },
    check_detail4:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=3'
      })
    },
    check_detail5:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=4'
      })
    },
    check_detail6:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=5'
      })
    },
    check_detail7:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=6'
      })
    },
    check_detail8:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=7'
      })
    },
    check_detail9:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=8'
      })
    },
    check_detail10:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=9'
      })
    },
    check_detail11:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=10'
      })
    },
    check_detail12:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=11'
      })
    },
    check_detail13:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=12'
      })
    },
    check_detail14:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=13'
      })
    },
    check_detail15:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=14'
      })
    },
    check_detail16:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=15'
      })
    },
    check_detail17:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=16'
      })
    },
    check_detail18:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=17'
      })
    },
    check_detail19:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=18'
      })
    },
    check_detail20:function(){
      console.log('heihei')
      wx.navigateTo({
        url:'../content/content?id=19'
      })
    },
  })